services:
  - type: web
    name: ai-task-frontend
    env: static
    rootDir: ./ai-task-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free

  - type: web
    name: ai-task-backend
    env: docker
    rootDir: ./ai-task-backend
    plan: free
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://aianurag_db_user:Anuragg2508@cluster98.2spqwg5.mongodb.net/ai-tasks?appName=Cluster98"
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true

  - type: worker
    name: ai-task-worker
    env: docker
    rootDir: ./ai-task-backend/worker
    plan: free
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://aianurag_db_user:Anuragg2508@cluster98.2spqwg5.mongodb.net/ai-tasks?appName=Cluster98"
      - key: REDIS_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
