apiVersion: v1
kind: Secret
metadata:
  name: ai-task-secret
  namespace: ai-platform
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb:27017/ai-tasks"
  JWT_SECRET: "k8ssupersecretjwtkeythatshouldbechangedinproduction"
